#!/usr/bin/env node
// Generate web/src/generated/personas.ts from the agents/ roster.
//
// The groupchat pipeline loads personas from this manifest, so adding a
// role under agents/<team>/<role>/agent.md and re-running this script makes
// it selectable with no engine edit (iterative-groupchat spec, sub-issue 3).
//
//     node scripts/build_personas.mjs
//
import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const AGENTS = join(ROOT, "agents");
const OUT = join(ROOT, "web", "src", "generated", "personas.ts");

const FM = /^---\n([\s\S]*?)\n---\n?([\s\S]*)$/;

function parse(path) {
  const text = readFileSync(path, "utf8");
  const m = FM.exec(text);
  if (!m) return null;
  const fm = {};
  for (const line of m[1].split("\n")) {
    const i = line.indexOf(":");
    if (i > 0) fm[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  return { fm, charter: m[2].trim() };
}

const personas = [];
for (const team of readdirSync(AGENTS)) {
  const teamDir = join(AGENTS, team);
  if (team === "TEMPLATE" || !statSync(teamDir).isDirectory()) continue;
  for (const role of readdirSync(teamDir)) {
    const roleDir = join(teamDir, role);
    const agentMd = join(roleDir, "agent.md");
    let st;
    try { st = statSync(roleDir); } catch { continue; }
    if (!st.isDirectory()) continue;
    let parsed;
    try { parsed = parse(agentMd); } catch { continue; }
    if (!parsed) continue;
    const { fm, charter } = parsed;
    personas.push({
      id: `${team}/${role}`,
      team,
      role,
      name: fm.name || `${team}-${role}`,
      description: (fm.description || "").split(/(?<=[.!?])\s/)[0],
      model: fm.model || "sonnet",
      tools: (fm.tools || "").split(",").map((t) => t.trim()).filter(Boolean),
      charter,
    });
  }
}
personas.sort((a, b) => a.id.localeCompare(b.id));

// Proximity rank per agents/ORCHESTRATION.md: security & legal enter first,
// logicians last; everything else in the middle.
const RANK = { security: 1, legal: 2, pm: 3, backend: 3, logicians: 6 };
const withRank = personas.map((p) => ({ ...p, proximity: RANK[p.team] ?? 4 }));

const banner =
  "// GENERATED by scripts/build_personas.mjs — do not edit by hand.\n" +
  "// Regenerate after changing agents/<team>/<role>/agent.md.\n";

const body =
  banner +
  "\nexport interface Persona {\n" +
  "  id: string;\n  team: string;\n  role: string;\n  name: string;\n" +
  "  description: string;\n  /** frontmatter tier alias: opus | sonnet | haiku | fable, or a concrete id */\n" +
  "  model: string;\n  tools: string[];\n" +
  "  /** proximity rank for consultation ordering (lower = earlier) */\n" +
  "  proximity: number;\n  /** the full agent.md charter, used as the persona system prompt */\n" +
  "  charter: string;\n}\n\n" +
  "export const PERSONAS: Persona[] = " +
  JSON.stringify(withRank, null, 2) +
  ";\n\nexport const PERSONA_BY_ID: Record<string, Persona> = Object.fromEntries(\n" +
  "  PERSONAS.map((p) => [p.id, p]),\n);\n";

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, body);
console.log(`wrote ${OUT}: ${withRank.length} personas`);
