#!/usr/bin/env python3
"""Generate docs/repo-map.md — a compact where-is-everything index.

Token economy (the repo's whole ethos): an agent that reads one terse map to
locate a thing spends far fewer tokens than one that greps and reads its way
to it. This is the *navigation* index — path → one-line purpose for every
script, doc, environment file, and team. Agent *detail* (persona/model/tools)
lives in the generated `agents/INDEX.md`; this map points there rather than
duplicating 95 rows.

Deterministic and idempotent, so `scripts/verify.py`'s `repo_map_fresh`
verifier can assert it is current. Run from the repo root:
    python3 scripts/build_repo_index.py
"""
import glob
import os
import re
import sys

OUT = "docs/repo-map.md"

# Top-level entries get a hand-written one-liner (their purpose isn't in a
# parseable first line); everything below is derived from the files.
LAYOUT = [
    ("agents/", "The brains: one folder per team, per role `agent.md` + `SPEC.md`. Roster detail in `agents/INDEX.md`."),
    ("environments/", "The hands: where an agent runs and what it can reach — network policy, permissions, MCP scoping, secrets, session lifecycle."),
    ("docs/", "Conventions, sprint logs, PRDs, backlog, OPSEC, and this map."),
    ("scripts/", "Stdlib-only tooling: roster build/lint, comms + credit + skills audits, and the verifier registry."),
    ("CLAUDE.md", "Session operating manual — what to do on start, docs convention, workflow, roster rules."),
    ("README.md", "Philosophy and the brains/hands split."),
]


def first_purpose(path):
    """One-line purpose: a .py module's first docstring line, or a .md file's
    H1 text (falling back to its first non-blank, non-heading line)."""
    try:
        text = open(path, encoding="utf-8").read()
    except OSError:
        return ""
    if path.endswith(".py"):
        m = re.search(r'^\s*(?:r|u)?"""(.*?)(?:"""|$)', text, re.S | re.M)
        if m:
            return m.group(1).strip().splitlines()[0].strip()
        return ""
    # markdown: prefer the first H1, else first meaningful line
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("# "):
            return s[2:].strip()
    for line in text.splitlines():
        s = line.strip()
        if s and not s.startswith("#") and not s.startswith("|"):
            return s
    return ""


def _rows(paths, base=""):
    rows = []
    for p in paths:
        label = p[len(base):] if base and p.startswith(base) else p
        rows.append((label, first_purpose(p)))
    return rows


def render():
    lines = [
        "# Repo map",
        "",
        "Generated by `scripts/build_repo_index.py` — do not edit by hand.",
        "Path → purpose, so a task can locate a file without grepping the tree.",
        "Agent roster detail is in [`agents/INDEX.md`](../agents/INDEX.md).",
        "",
        "## Layout",
        "",
        "| Path | Purpose |",
        "|---|---|",
    ]
    for path, purpose in LAYOUT:
        lines.append(f"| `{path}` | {purpose} |")

    # Teams: role count + the team README's first line as the one-liner.
    lines += ["", "## Teams (`agents/`)", "",
              "| Team | Roles | Charter |", "|---|---|---|"]
    for team_dir in sorted(glob.glob("agents/*/")):
        team = team_dir.rstrip("/").split("/")[-1]
        if team == "TEMPLATE":
            continue
        n = len(glob.glob(f"agents/{team}/*/agent.md"))
        readme = f"agents/{team}/README.md"
        charter = first_purpose(readme) if os.path.exists(readme) else ""
        lines.append(f"| [`{team}`]({team_dir}) | {n} | {charter} |")

    # Scripts
    lines += ["", "## Scripts (`scripts/`)", "",
              "| Script | Purpose |", "|---|---|"]
    for path, purpose in _rows(sorted(glob.glob("scripts/*.py")), "scripts/"):
        lines.append(f"| `{path}` | {purpose} |")
    verifiers = sorted(
        p for p in glob.glob("scripts/verifiers/*.py")
        if not os.path.basename(p).startswith("_")
    )
    if verifiers:
        lines.append(f"| `verifiers/` | {len(verifiers)} single-property "
                     "machines run by `verify.py` — see `verify.py --list`. |")

    # Environments
    lines += ["", "## Environments (`environments/`)", "",
              "| File | Purpose |", "|---|---|"]
    for path, purpose in _rows(sorted(glob.glob("environments/*.md")),
                               "environments/"):
        lines.append(f"| `{path}` | {purpose} |")

    # Top-level docs + key doc dirs
    lines += ["", "## Docs (`docs/`)", "",
              "| Doc | Purpose |", "|---|---|"]
    for path, purpose in _rows(sorted(glob.glob("docs/*.md")), "docs/"):
        lines.append(f"| `{path}` | {purpose} |")
    doc_dirs = sorted(d for d in glob.glob("docs/*/") if os.path.isdir(d))
    if doc_dirs:
        lines += ["", "| Doc dir | Contents |", "|---|---|"]
        for d in doc_dirs:
            name = d.rstrip("/").split("/")[-1]
            readme = os.path.join(d, "README.md")
            purpose = first_purpose(readme) if os.path.exists(readme) else \
                f"{len(glob.glob(d + '**/*.md', recursive=True))} file(s)"
            lines.append(f"| `docs/{name}/` | {purpose} |")

    return "\n".join(lines) + "\n"


def main():
    content = render()
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"wrote {OUT}: {content.count(chr(10))} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
